version: '3'

services:
  vpn:
    image: ipsec-vpn-server:dev
    restart: always
    env_file:
      - ./.env
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true
    hostname: ipsec-vpn-server
    container_name: ipsec-vpn-server
